[build]
base = "/"
command = "yarn build"
publish = "build/"

[build.processing]
skip-processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true

[[redirects]]
from = '/yieldfarmingama'
to = 'https://kogecoin.notion.site/KogeFarm-s-LIVE-YouTube-AMA-with-QuickSwap-Orbs-and-QiDAO-c08960f880e84ac5abc2c1f3096791f4'
status = 301
force = true
headers = {X-From = "Netlify"}

[context.deploy-preview.processing]
skip-processing = true

[context.deploy-preview.processing.css]
bundle = false
minify = false

[context.deploy-preview.processing.js]
bundle = false
minify = false

[context.deploy-preview.processing.images]
compress = false