[build]
base = "/"
command = "yarn build"
publish = "build/"

[build.processing]
skip-processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true

# [[redirects]]
# from = '/docs'
# to = 'https://koge.gitbook.io'
# status = 200
# force = true
# headers = {X-From = "Netlify"}

[context.deploy-preview.processing]
skip-processing = true

[context.deploy-preview.processing.css]
bundle = false
minify = false

[context.deploy-preview.processing.js]
bundle = false
minify = false

[context.deploy-preview.processing.images]
compress = false

[[headers]]
  for = "/*"
  [headers.values]
  Clear-Site-Data = "\"*\""
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
