[build]
base = "/"
command = "yarn build"
publish = "build/"

[build.processing]
skip-processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.images]
compress = true

# [[redirects]]
# from = '/docs'
# to = 'https://koge.gitbook.io'
# status = 200
# force = true
# headers = {X-From = "Netlify"}
